name: 💻 Frontend Task
description: Track UI/UX feature or bug for Tourii frontend
title: "[FE] <Short title here>"
labels: ["frontend", "type: task"]

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High 🔥
        - Medium ⚠️
        - Low 🧊
    validations:
      required: true

  - type: input
    id: sprint
    attributes:
      label: Sprint
      placeholder: e.g. Sprint 3, Backlog

  - type: textarea
    id: description
    attributes:
      label: Task Description
      placeholder: Implement feature X, build page Y...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Component renders correctly
        - [ ] Mobile responsive
        - [ ] Connected to backend via API

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies
      options:
        - label: Waiting for backend endpoint
        - label: Blocked by design
        - label: None