name: 💻 Frontend Task
description: Track UI/UX feature or bug for Tourii frontend
title: "[FE] <Short title here>"
labels: ["frontend", "type: task"]

body:

  - type: markdown
    id: task_overview
    attributes:
      value: |
        ## 💻 [FE] <Feature or Task Title Here>
        
        ---
        
        **Description:**  
        <Provide a concise description of the task here, e.g., Implement feature X, build page Y.>
        
        **Tasks:**
        - [ ] <Task 1>
        - [ ] <Task 2>
        - [ ] <Task 3>
        - [ ] <Task 4>
        
        **Props:**
        - <List any props or state variables required (if none, write 'None')>
        
        **Pseudocode:**
        ```tsx
        <Provide pseudocode or a sample code block here>
        ```
        
        **Acceptance Criteria:**
        - [ ] <Criterion 1>
        - [ ] <Criterion 2>
        - [ ] <Criterion 3>
        
        ---
        
  - type: textarea
    id: additional_acceptance
    attributes:
      label: Additional Acceptance Criteria
      placeholder: |
        - [ ] Component renders correctly
        - [ ] Mobile responsive
        - [ ] Connected to backend via API

  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies
      options:
        - label: Waiting for backend endpoint
        - label: Blocked by design
        - label: None
